# Generated by Django 6.0.5 on 2026-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Тело письма"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=250, verbose_name="Тема письма"),
        ),
    ]
