# Generated by Django 6.0.5 on 2026-06-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_alter_message_body_alter_message_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["status"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                help_text="Выберете сообщение для отправки рассылки",
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing_service.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Выберете получателей рассылки", related_name="mailings", to="mailing_service.recipient"
            ),
        ),
    ]
