# Generated by Django 6.0.5 on 2026-06-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["message"],
                "permissions": [("can_deactivate_mailing", "Может отключать рассылки")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
